### PR TITLE
fix(server): `http/https` protocol frame read fix

### PR DESCRIPTION
**Pull request by dalisoft**

### CODE REVIEW

**Comment by mifi** [comment]
Hi! can you please describe why this is needed? uri2path should already strip off http/https, no?

**Comment by dalisoft** [comment]
@mifi Based on my testings, no, it does not works. This PR should fix issue

**Comment by mifi** [comment]
Could you provide an example url that doesnt work?

**Comment by dalisoft** [comment]
Any https url, aws s3 url for example. Seems work for you, so issue may be in my machine

**Pull request closed without merging**
